name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: pnpm

            - run: pnpm i --frozen-lockfile
            - run: pnpm run build
            - run: pnpm run test
